### DISCUSSION TITLE
Reading keys from environment variables

### DISCUSSION THREAD

**Discussion by omarkurt** [projectdiscovery/cloudlist#248] [Ideas]
Hello PD team,
I want to use environment variables instead of adding them in the configuration file as plaintext.

For example,

```yaml
- provider: aws 
  id: staging
  aws_access_key: $ACCESS_KEY
  aws_secret_key: $SECRET_KEY
```

I did not see any information regarding using ENV variables.
