### ISSUE TITLE
Reading keys from environment variables

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/cloudlist#249]
### Discussed in https://github.com/projectdiscovery/cloudlist/discussions/248

<div type='discussions-op-text'>

<sup>Originally posted by **omarkurt** November 11, 2022</sup>
Hello PD team,
I want to use environment variables instead of adding them in the configuration file as plaintext.

For example,

```yaml
- provider: aws 
  id: staging
  aws_access_key: $ACCESS_KEY
  aws_secret_key: $SECRET_KEY
```

I did not see any information regarding using ENV variables.</div>

---
**Note:** 

Probably support to add in https://github.com/projectdiscovery/goflags so all other PD projects can utilize this enhancement.
