### ISSUE TITLE
Add custom provider support

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/cloudlist#602]
**Describe the solution you'd like**
custom provider support to fetch subdomains from custom source which could be any public or authed URLs containing subdomain data in plain text or json and other format.

**Note**: regardless of the format, we just need to parse out the subdomin data.

```yaml
# provider is the name of the provider
provider: custom
id: test
# urls is a list of API endpoints or resources to be accessed
urls:
  - https://api.example.com/resource1
  - https://api.example.com/resource2
# headers is a map of custom headers to be included in requests
headers:
  Authorization: $CUSTOM_AUTH_TOKEN
  Content-Type: application/json
  X-Custom-Header: $CUSTOM_HEADER
```

Reference - https://projectdiscovery.featurebase.app/p/custom-connect
