### ISSUE TITLE
Services filter support via provider config same as CLI

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/cloudlist#652]
Currently one can filter services to enumerate from providers, same ability can be exposed to provider config file as well for better control when running using provider file.

```
   -s, -service value  query and display results from given service (comma-separated)) (default compute,consul,apigateway,cloud-run,publicip,cloud-function,app,s3,domain,vm,cloudfront,ecs,droplet,service,dns,lightsail,ingress,alb,instance,elb,lambda,ec2,nomad,eks,custom,route53,gke,fastly)
```

Example:

```yaml
- # provider is the name of the provider
  provider: aws
  # id is the name defined by user for filtering (optional)
  id: staging
  # aws_access_key is the access key for AWS account
  aws_access_key: $AWS_ACCESS_KEY
  # aws_secret_key is the secret key for AWS account
  aws_secret_key: $AWS_SECRET_KEY
  # aws_session_token session token for temporary security credentials retrieved via STS (optional)
  aws_session_token: $AWS_SESSION_TOKEN
+  services:
+    - "s3"
+    - "instance"
```
