### ISSUE TITLE
[issue] issue in runner:  line 21: cannot unmarshal !!map into schema.Options

### ISSUE THREAD

**Issue by R34LUS3R** [projectdiscovery/cloudlist#8]
**Describe the bug**
I am not able to run Cloudlist as there is some kind of error.
I have tried the release, build it my self but still, the error is the same

**Error**
```
root@root:~/cloudlist/cmd/cloudlist# ./cloudlist -provider aws
v.0.0.1
Could not create runner: yaml: unmarshal errors:
line 21: cannot unmarshal !!map into schema.Options
```

**Go Version**
`go version go1.15.5 linux/amd64`

**Comment by rtcms** [comment]
+1 I am also getting the same issue

**Comment by ehsandeep** [comment]
@rtcms @R34LUS3R the above error is related to a syntax error in the config file, as example config is shared in the readme to just copy the below config and replace the values based on your provided and run as `cloudlist -config test.yaml` and it should be working.

```yaml
- # provider is the name of the provider
  provider: do
  profile: xxxx
  digitalocean_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
